enyo.depends(
    "source/App.js",
    "source/MainView.js",
    "source/StatusHeader.js",
    "source/Plugin.js",
    "source/Controls.js",
    "source/VirtualList.js",
    "source/Queue.js",
    "source/Playlists.js",
    "source/Prefs.js",
    "source/About.js",
    "source/SleepSettings.js",
    "source/Alarm.js",
    "source/SearchInput.js",
    "source/MPC.css"
);
