#ifndef MPC_PLUGIN_H
#define MPC_PLUGIN_H

#define EVENT_CODE_CONNECT 0
#define EVENT_CODE_PLAY 1
#define EVENT_CODE_PLAY_BY_ID 2
#define EVENT_CODE_STOP 3
#define EVENT_CODE_PAUSE 4
#define EVENT_CODE_TIMER 5
#define EVENT_CODE_SET_VOLUME 6
#define EVENT_CODE_SET_RANDOM 7
#define EVENT_CODE_SET_REPEAT 8
#define EVENT_CODE_NEXT 9
#define EVENT_CODE_LOAD_PLAYLIST 10
#define EVENT_CODE_CROP 11

#endif
